language: node_js
node_js:
- '12'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=lamutuellegenerale)
  - secure: BzFrNjVCt200CpE7I48nZxkuazvaXZYdLQFSpj4iAZCXUfyGCq4nyH2bwVw7QLLvkkk761l56Vo+dANnnoM58OzcgID7c7J2uAvFUvBA4qcQLhAs22BJRqE/WIqcFh/lJdAVaxsPOLdkTIk6xb9CLGQ2XnBDX+gXuHe6flyetUSr+HAuinnUL66+fcDtFYohwfzRZpyCV3ewGsTjxCzhYboOFmFt2OPb8BPW0s0z/nWB4z5gFFxqGXp5eyEejI1u6BD1L8wlFN6u/ipto7oIBvsMNf8pHAIPzKv6VFuiqMFORlDTJerDX4RCfRwklupQMJLztLWecjdLW+nFrAdQejgqpyTYxwsVmPF+F/BSPmvZGgvfHKEpnMa9ZFXr68AAeCopEFfdFq58kOWxlujk3PWSbT+vsrCzpQzoSKuE2wA3bfloazzkfcBycEBkwTYB44YEemjCb6EwFpyPOtmVSyeqkuvUoV18hTJdwEkWTjqf5QaP/joMa3Ei/OTG2P8SRANat+YlnnssKTczFXeqDuir1aXTQEYPAsekRiDcuAjGxCbCDSvokEX/6YFtJEQxqhr0Nes/N79EyBrvtMpRV3USREZVkR6agamHvaU4qs5QQ2zGn1hJq2lW2U1iBlONLoeM64CPmkB+0tpl1HfEdETycF8pEHT5tysbFpuMHJE=
  # MATTERMOST_HOOK_URL
  - secure: NCFuqDqnBs9F710bgkiX2FEf2X62jZRhd2t3iVhwOSe+QebmU8vkPl6dIYjz47zEGuZEAZ1djTvSGnblLiYpxzMjCmytS7hqb5yZS19YXVRdp/9bLWGd7WYr6L/7y9pvJ/f07yxtoS+GMB8M0uu0XFbNc/UVVciptwohN8/ydPCgX/31pbtp4FaZq/L5EaJQSyFWpV4I51ZbaVIJL/sdgo9bs2fWjIHFD8n6BOvalFn62MP4+YbO+mC+ddt+XYoFj120EIg0f70x1xzXipl8n/iO0UP/Wiwewn/i2ikdRRG9vtTvqMj5whZPONPDjkFIOK+9zKb7FWr6as5ElRtJgrnbgPM7VlGOerB+uNiEkQPhEmSDXH7aR85CnRdpj219+NkJZNWYdDCEc7Ulm8XuqGx+uafdchQJWI0iGZ7wXVjGliAqQIq7GYDSDjtg7LOGHE1iML3B5SVQalQ7WU4Dw2PZzys+r1uJIxC1uI2YCeJhtkO7MQPAHJZ3GN4H6FyG1YzoLoBtf4d73QTpGZgYS2UkdMtuMVdZqf1X8K2PWm+W/9WBsqxpzpNoOg710xj9MUtAULYw5DQiASzu6Je7Uu9HS81w2j42JK6uzCTssfi2O+V1ctJZLQcMd+KaG5dPaySKXkAGQf2BysSlyaQuG+IKgmTDLfalBVTzy1bTMkA=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_3d1203bc142c_key -iv $encrypted_3d1203bc142c_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
